title = "Feisky"
baseURL = "https://feisky.xyz/"
languageCode = "zh-cn"
theme = "hyde-hyde"
publishDir = "docs"
disqusShortname = "feisky"
hasCJKLanguage = true
googleAnalytics = "UA-69699206-1"
metaDataFormat = "yaml"
enableEmoji = true
buildDrafts = true
enableRobotsTXT = true

[params]
  author = "Pengfei Ni"
  themeColor = "theme-base-0d"
  description = "Notes about anything"
  copyright = "feiskyer"
  license = "CC BY-SA 4.0"
  licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"
  showBuiltWith = true
  highlightjs = true
  highlightjsstyle = "github"
  paginate = 5
  toc = "tocbot"
  postNavigation = true
  relatedPosts = true
  disqusShortname = "feisky"
  googleAnalytics = "UA-69699206-1"

[params.social]
	twitter = "feisky"
	github = "feiskyer"

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[[menu.main]]
    name = "机器学习"
    weight = 30
    url = "/machine-learning/"

[[menu.main]]
    name = "SDN网络"
    weight = -1
    url = "https://sdn.feisky.xyz"

[[menu.main]]
    name = "Kubernetes指南"
    weight = -100
    url = "https://kubernetes.feisky.xyz"

[[menu.main]]
    name = "Linux性能优化实战"
    weight = -90
    url = "https://time.geekbang.org/column/intro/100020901"

[[menu.main]]
    name = "关于我"
    weight = 100
    url = "/about/"
