title = "Feisky"
baseURL = "https://feisky.xyz/"
languageCode = "zh-cn"
theme = "hyde-hyde"
publishDir = "docs"
disqusShortname = "feisky"
hasCJKLanguage = true
googleAnalytics = "UA-69699206-1"
metaDataFormat = "yaml"
enableEmoji = true
buildDrafts = false
enableRobotsTXT = true

[params]
  author = "Pengfei Ni"
  themeColor = "theme-base-0d"
  copyright = "feiskyer"
  license = "CC BY-SA 4.0"
  licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"
  showBuiltWith = true
  highlightjs = true
  highlightjsstyle = "monokai"
  paginate = 5
  toc = "tocbot"
  postNavigation = true
  relatedPosts = true
  disqusShortname = "feisky"
  googleAnalytics = "UA-69699206-1"

[params.social]
	twitter = "feisky"
	github = "feiskyer"
  gravatar = "feiskyer@gmail.com"

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[[menu.main]]
    name = "微信公众号"
    weight = 30
    url = "/assets/mp.png"

[[menu.main]]
    name = "SDN网络指南"
    weight = 20
    url = "https://sdn.feisky.xyz"

[[menu.main]]
    name = "Kubernetes指南"
    weight = 10
    url = "https://kubernetes.feisky.xyz"

[[menu.main]]
    name = "知乎专栏"
    weight = 40
    url = "https://zhuanlan.zhihu.com/kubernetes"

[[menu.main]]
    name = "Linux性能优化实战"
    weight = 1
    url = "https://time.geekbang.org/column/intro/100020901"

[[menu.main]]
    name = "关于我"
    weight = 100
    url = "/about/"
